-- CreateEnum
CREATE TYPE "FestivalStatus" AS ENUM ('UPCOMING', 'LIVE', 'FINISHED');

-- CreateTable
CREATE TABLE "WebsiteSettings" (
    "id" INTEGER NOT NULL DEFAULT 1,
    "festivalName" TEXT NOT NULL DEFAULT 'Waterfall Festival Koh Phangan',
    "tagline" TEXT NOT NULL DEFAULT 'Nature. Music. Freedom.',
    "location" TEXT NOT NULL DEFAULT 'Koh Phangan, Thailand',
    "venue" TEXT NOT NULL DEFAULT 'Waterfall Party Venue',
    "startDate" TIMESTAMP(3),
    "endDate" TIMESTAMP(3),
    "timezone" TEXT NOT NULL DEFAULT 'Asia/Bangkok',
    "festivalStatus" "FestivalStatus" NOT NULL DEFAULT 'UPCOMING',
    "defaultLanguage" TEXT NOT NULL DEFAULT 'English',
    "websiteUrl" TEXT NOT NULL DEFAULT '',
    "publicEmail" TEXT NOT NULL DEFAULT '',
    "supportEmail" TEXT NOT NULL DEFAULT '',
    "phoneNumber" TEXT NOT NULL DEFAULT '',
    "whatsappNumber" TEXT NOT NULL DEFAULT '',
    "address" TEXT NOT NULL DEFAULT '',
    "googleMapsUrl" TEXT NOT NULL DEFAULT '',
    "contactFormEnabled" BOOLEAN NOT NULL DEFAULT true,
    "instagramUrl" TEXT NOT NULL DEFAULT '',
    "facebookUrl" TEXT NOT NULL DEFAULT '',
    "tiktokUrl" TEXT NOT NULL DEFAULT '',
    "youtubeUrl" TEXT NOT NULL DEFAULT '',
    "spotifyUrl" TEXT NOT NULL DEFAULT '',
    "showSocialLinksInFooter" BOOLEAN NOT NULL DEFAULT true,
    "assistantEnabled" BOOLEAN NOT NULL DEFAULT true,
    "assistantName" TEXT NOT NULL DEFAULT 'Waterfall Assistant',
    "assistantWelcomeMessage" TEXT NOT NULL DEFAULT 'Hi! Ask me about tickets, events, the venue, or festival information.',
    "assistantPlaceholder" TEXT NOT NULL DEFAULT 'Ask about the festival...',
    "assistantOfflineMessage" TEXT NOT NULL DEFAULT 'The assistant is temporarily unavailable. Please contact our support team.',
    "escalationEmail" TEXT NOT NULL DEFAULT '',
    "eventsPageEnabled" BOOLEAN NOT NULL DEFAULT true,
    "ticketsPageEnabled" BOOLEAN NOT NULL DEFAULT true,
    "experiencePageEnabled" BOOLEAN NOT NULL DEFAULT true,
    "galleryPageEnabled" BOOLEAN NOT NULL DEFAULT true,
    "faqPageEnabled" BOOLEAN NOT NULL DEFAULT true,
    "newsletterEnabled" BOOLEAN NOT NULL DEFAULT false,
    "primaryAccent" TEXT NOT NULL DEFAULT '#7c3aed',
    "secondaryAccent" TEXT NOT NULL DEFAULT '#22d3ee',
    "logoUrl" TEXT NOT NULL DEFAULT '/logo.png',
    "compactLogoUrl" TEXT NOT NULL DEFAULT '/logo-mark.png',
    "faviconUrl" TEXT NOT NULL DEFAULT '/favicon.ico',
    "socialImageUrl" TEXT NOT NULL DEFAULT '/social-share.jpg',
    "footerDescription" TEXT NOT NULL DEFAULT 'Experience Thailand''s most unforgettable music festival in the heart of Koh Phangan.',
    "footerCopyright" TEXT NOT NULL DEFAULT '© Waterfall Festival. All rights reserved.',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "WebsiteSettings_pkey" PRIMARY KEY ("id")
);
